---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: console-od
  labels:
    abcdesktop/role: console
spec:
  selector:
    matchLabels:
      run: console-od
  replicas: {{ .Values.console.replicaCount }}
  template:
    metadata:
      labels:
        run: console-od
        type: admin-console
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: console
        imagePullPolicy: Always
        image: {{ .Values.console.image }}:{{ .Values.console.tag }}
        ports:
          - containerPort: 80
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: {{ .Values.console.resources.limits.cpu }}
            memory: {{ .Values.console.resources.limits.memory }}
          requests:
            cpu: {{ .Values.console.resources.requests.cpu }}
            memory: {{ .Values.console.resources.requests.memory }}
        volumeMounts:
          - name: version-config-volume
            mountPath: /usr/share/nginx/html/config/versionConfig.json
            subPath: versionConfig.json
            readOnly: true
      volumes:
        - name: version-config-volume
          configMap:
            name: abcdesktop-version-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
