---
apiVersion: v1
kind: ConfigMap
metadata:
  name: abcdesktop-gshadow-templatefile
  namespace: {{ .Release.Namespace }}
data:
  gshadow: |
    sudo:*::{{ uid }}
    lpadmin:!::root,{{ uid }}
    {{ gid }}:!::{{ uid }}
