apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: generate-jwtdesktopsigning-keys
  # annotations:
  #   "helm.sh/hook": post-install,post-upgrade
  #   "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      serviceAccountName: pyos-serviceaccount
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: generate-keys
        imagePullPolicy: IfNotPresent
        image: {{ .Values.keysgenerator.image }}:{{ .Values.keysgenerator.tag }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            openssl genrsa -out abcdesktop_jwt_desktop_signing_private_key.pem {{ .Values.keysgenerator.jwtdesktopsigningkeylength }}  && \
            openssl rsa -in abcdesktop_jwt_desktop_signing_private_key.pem -outform PEM -pubout -out abcdesktop_jwt_desktop_signing_public_key.pem && \
            if ! kubectl get secret abcdesktopjwtdesktopsigning --namespace={{ .Release.Namespace }} >/dev/null 2>&1; then
              if kubectl create secret generic abcdesktopjwtdesktopsigning --from-file=abcdesktop_jwt_desktop_signing_private_key.pem --from-file=abcdesktop_jwt_desktop_signing_public_key.pem --namespace={{ .Release.Namespace }};
              then
                echo "Failed to create secret"
                exit 1
              fi
            else
              echo "Secret already exists"
              exit 0
            fi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
