apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: generate-jwtdesktoppayload-keys
spec:
  template:
    spec:
      serviceAccountName: pyos-serviceaccount
      restartPolicy: OnFailure
      ttlSecondsAfterFinished: 5
      containers:
      - name: generate-keys
        imagePullPolicy: Always
        image: {{ .Values.keysgenerator.image }}:{{ .Values.keysgenerator.tag }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            openssl genrsa -out abcdesktop_jwt_desktop_payload_private_key.pem 1024 && \
            openssl rsa -in abcdesktop_jwt_desktop_payload_private_key.pem -outform PEM -pubout -out  _abcdesktop_jwt_desktop_payload_public_key.pem && \
            openssl rsa -pubin -in _abcdesktop_jwt_desktop_payload_public_key.pem -RSAPublicKey_out -out abcdesktop_jwt_desktop_payload_public_key.pem && \
            kubectl create secret generic abcdesktopjwtdesktoppayload --from-file=abcdesktop_jwt_desktop_payload_private_key.pem --from-file=abcdesktop_jwt_desktop_payload_public_key.pem --namespace={{ .Release.Namespace }} 
