# mongo-keyfile-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-keyfile-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    abcdesktop/role: mongodb
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-weight": "-50"    