---
{{- $mongo_root_password := "" }}
{{- $mongo_password := "" }}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace "secret-mongodb") }}
{{- if $existing }}
  {{- $mongo_root_password = (index $existing.data "MONGO_ROOT_PASSWORD" | b64dec) }}
  {{- $mongo_password = (index $existing.data "MONGO_PASSWORD" | b64dec) }}
{{- else }}
  {{- $mongo_root_password = (include "abcdesktop.mongorootpassword" .) }}
  {{- $mongo_password = (include "abcdesktop.mongopassword" .) }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: secret-mongodb
  labels:
    abcdesktop/role: secret-mongodb
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: 'root'
  MONGO_ROOT_PASSWORD: {{ $mongo_root_password }}
  MONGO_USERNAME: 'pyos'
  MONGO_PASSWORD: {{ $mongo_password }}
  MONGO_USERS_LIST: 'pyos:readWrite:{{ $mongo_password }}'
  MONGO_DBS_LIST: 'image,fail2ban,loginHistory,applications,profiles,desktop'
  MONGODB_URL: 'mongodb://pyos:{{ $mongo_password }}@mongodb'
