---
apiVersion: v1
kind: ConfigMap
metadata:
  name: abcdesktop-passwd-templatefile
  namespace: {{ .Release.Namespace }}
data:
  passwd: |
    {{ uid }}:x:{{ uidNumber }}:{{ gidNumber }}:{{ gecos }}:{{ homeDirectory }}:{{ loginShell }}