---
apiVersion: v1
kind: ConfigMap
metadata:
  name: abcdesktop-shadow-templatefile
  namespace: {{ .Release.Namespace }}
data:
  shadow: |
    {{ "{{" }} uid {{ "}}" }}:{{ "{{" }} sha512 {{ "}}" }}:19080:0:99999:7:::