kind: Service
apiVersion: v1
metadata:
  name: speedtest
  namespace: {{ .Release.Namespace }}
  labels:
    abcdesktop/role: speedtest
spec:
  selector:
    run: speedtest-od
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
