kind: Service
apiVersion: v1
metadata:
  name: website
  namespace: {{ .Release.Namespace }}
  labels:
    abcdesktop/role: website
spec:
  selector:
    run: nginx-od
  ports:
  - protocol: TCP
    port: 80
    name: http