---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "abcdesktop.fullname" . }}-abcdesktop-config
  labels:
    {{- include "abcdesktop.labels" . | nindent 4 }}
data: |-
  {{- range $key, $value := .Values.config }}
  {{ $key }}:{{ $value }}
  {{- end }}
