
---
apiVersion: v1 
kind: Service 
metadata: 
  name: {{ include "abcdesktop.fullname" . }}-desktop
  labels:
    abcdesktop/role: desktop
    {{- include "abcdesktop.labels" . | nindent 4 }}
spec: 
  clusterIP: None
  selector:
    type: x11server
    {{- include "abcdesktop.selectorLabels" . | nindent 4 }}
