apiVersion: v2
name: abcdesktop
description: ABCDesktop helm chart
type: application
version: 4.4.12
appVersion: "4.4.12"
icon: https://www.abcdesktop.io/img/abcdesktop.svg
keywords: [abcdesktop, vdi, desktop, kubernetes]
kubeVersion: ">=1.28.0-0"
annotations:
  artifacthub.io/signKey: |
    fingerprint: 0x351794CC
    url: http://keyserver1.pgp.com/vkd/DownloadKey.event?keyid=0xD765E44E351794CC
